#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : numba
Version  : 0.39.0
Release  : 17
URL      : https://github.com/numba/numba/archive/0.39.0.tar.gz
Source0  : https://github.com/numba/numba/archive/0.39.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: numba-bin
Requires: numba-python3
Requires: numba-license
Requires: numba-python
Requires: argparse
Requires: llvmlite
Requires: numpy
BuildRequires : llvmlite
BuildRequires : numpy
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
This directory contains python script for benchmarking the performance of
numba.

%package bin
Summary: bin components for the numba package.
Group: Binaries
Requires: numba-license

%description bin
bin components for the numba package.


%package license
Summary: license components for the numba package.
Group: Default

%description license
license components for the numba package.


%package python
Summary: python components for the numba package.
Group: Default
Requires: numba-python3

%description python
python components for the numba package.


%package python3
Summary: python3 components for the numba package.
Group: Default
Requires: python3-core

%description python3
python3 components for the numba package.


%prep
%setup -q -n numba-0.39.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530973994
find -name "*pyx" | xargs touch ||:
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/numba
cp LICENSE %{buildroot}/usr/share/doc/numba/LICENSE
cp buildscripts/condarecipe.local/license.txt %{buildroot}/usr/share/doc/numba/buildscripts_condarecipe.local_license.txt
cp buildscripts/condarecipe.hsa/license.txt %{buildroot}/usr/share/doc/numba/buildscripts_condarecipe.hsa_license.txt
cp buildscripts/condarecipe.buildbot/license.txt %{buildroot}/usr/share/doc/numba/buildscripts_condarecipe.buildbot_license.txt
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/numba
/usr/bin/pycc

%files license
%defattr(-,root,root,-)
/usr/share/doc/numba/LICENSE
/usr/share/doc/numba/buildscripts_condarecipe.buildbot_license.txt
/usr/share/doc/numba/buildscripts_condarecipe.hsa_license.txt
/usr/share/doc/numba/buildscripts_condarecipe.local_license.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
