#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : numba
Version  : 0.48.0
Release  : 40
URL      : https://github.com/numba/numba/archive/0.48.0/numba-0.48.0.tar.gz
Source0  : https://github.com/numba/numba/archive/0.48.0/numba-0.48.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: numba-bin = %{version}-%{release}
Requires: numba-license = %{version}-%{release}
Requires: numba-python = %{version}-%{release}
Requires: numba-python3 = %{version}-%{release}
Requires: funcsigs
Requires: llvmlite
Requires: numpy
Requires: setuptools
Requires: singledispatch
BuildRequires : buildreq-distutils3
BuildRequires : funcsigs
BuildRequires : llvmlite
BuildRequires : numpy
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : singledispatch

%description
# DAG Roadmap
This directory includes a representation of the Numba roadmap in the form of a
DAG.  We have done this to enable a highly granular display of enhancements to
Numba that also shows the relationships between these tasks. Many tasks have
prerequisites, and we've found that issue trackers, Kanban boards, and
time-bucketed roadmap documentation all fail to represent this information in
different ways.

%package bin
Summary: bin components for the numba package.
Group: Binaries
Requires: numba-license = %{version}-%{release}

%description bin
bin components for the numba package.


%package license
Summary: license components for the numba package.
Group: Default

%description license
license components for the numba package.


%package python
Summary: python components for the numba package.
Group: Default
Requires: numba-python3 = %{version}-%{release}

%description python
python components for the numba package.


%package python3
Summary: python3 components for the numba package.
Group: Default
Requires: python3-core

%description python3
python3 components for the numba package.


%prep
%setup -q -n numba-0.48.0
cd %{_builddir}/numba-0.48.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1580227330
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/numba
cp %{_builddir}/numba-0.48.0/LICENSE %{buildroot}/usr/share/package-licenses/numba/117656b1e78464bdd17abb947fa3152444c9e4bb
cp %{_builddir}/numba-0.48.0/buildscripts/condarecipe.local/license.txt %{buildroot}/usr/share/package-licenses/numba/117656b1e78464bdd17abb947fa3152444c9e4bb
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/numba
/usr/bin/pycc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/numba/117656b1e78464bdd17abb947fa3152444c9e4bb

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
